name: Build LaTex FHTW make like
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/checkout@v4
      - name: Compile Document 1
        uses: dante-ev/latex-action@latest
        with:
          root_file: diplom.tex
          working_directory: diplomathesis
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: BibTex
        uses: dante-ev/latex-action@latest
        with:
          root_file: diplom.aux
          working_directory: diplomathesis
          compiler: bibtex
          args: 
      - name: Compile Document 2
        uses: dante-ev/latex-action@latest
        with:
          root_file: diplom.tex
          working_directory: diplomathesis
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Compile Document 3
        uses: dante-ev/latex-action@latest
        with:
          root_file: diplom.tex
          working_directory: diplomathesis
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: Renning2003_TeachingByChat.pdf
          path: ./diplomathesis/diplom.pdf

