name: Build LaTex document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/checkout@v3
      - name: Compile Document
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          args: -interaction=nonstopmode -shell-escape
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: main.pdf
          path: ./main.pdf


